### ISSUE TITLE
How did you get the caption of the heat map ? Is it generated by gpt4-vision ?

### ISSUE THREAD

**Issue by Yang-bug-star** [AlexJJJChen/Climate-Zoo#1]

**Comment by AlexJJJChen** [comment]
To ensure the caption is accurate and without errors, we first generated a standard template for the caption, and then filled in the gaps in the template with ground truth data. You can see that the caption of each picture shares the same template.

**Comment by Yang-bug-star** [comment]
where do you put the caption data ？



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 25, 2024 22:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AlexJJJChen/Climate-Zoo] How did you get the caption of the heatmap ? Is it generated by gpt4-vision ? (Issue #1)




 
To ensure the caption is accurate and without errors, we first generated a standard template for the caption, and then filled in the gaps in the template with ground truth data. You can see that the caption of each picture shares the same template.

**Comment by AlexJJJChen** [comment]
> where do you put the caption data ？
> […](#)

In the QA Pairs datasets: https://drive.google.com/drive/folders/1VVcTpdM_XTLRFAWk3z5sU2W67Wr5tu-Z?usp=share_link
the answer of description question "can you describe the image..." is caption
